package compose

import (
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

// BaseCompose represents minimal structure needed to inspect base compose file.
type BaseCompose struct {
	Services map[string]ServiceDef `yaml:"services"`
}

type ServiceDef struct {
	Image         string `yaml:"image"`
	Ports         []any  `yaml:"ports"`
	Healthcheck   any    `yaml:"healthcheck"`
	ContainerName any    `yaml:"container_name"`
}

// GenerateOverrideYAML generates the compose-override.yml content.
func GenerateOverrideYAML(baseComposeContent, bubbleID string, envDirectives map[string]map[string]string) (string, error) {
	var base BaseCompose
	if err := yaml.Unmarshal([]byte(baseComposeContent), &base); err != nil {
		return "", fmt.Errorf("parsing base compose file: %w", err)
	}

	var sb strings.Builder
	sb.WriteString("# Generated by Bubble CLI. DO NOT EDIT.\n")
	sb.WriteString("services:\n")

	for svcName, svc := range base.Services {
		sb.WriteString(fmt.Sprintf("  %s:\n", svcName))
		sb.WriteString("    labels:\n")
		sb.WriteString("      bubble.managed: \"true\"\n")

		// Strip fixed container_name so parallel bubbles never collide
		if svc.ContainerName != nil {
			sb.WriteString("    container_name: !reset\n")
		}

		// Provide automatic healthcheck if missing for common databases
		if svc.Healthcheck == nil {
			if strings.Contains(svc.Image, "postgres") || strings.Contains(svcName, "postgres") {
				sb.WriteString("    healthcheck:\n")
				sb.WriteString("      test: [\"CMD-SHELL\", \"pg_isready -U postgres\"]\n")
				sb.WriteString("      interval: 1s\n")
				sb.WriteString("      timeout: 2s\n")
				sb.WriteString("      retries: 20\n")
			} else if strings.Contains(svc.Image, "redis") || strings.Contains(svcName, "redis") {
				sb.WriteString("    healthcheck:\n")
				sb.WriteString("      test: [\"CMD\", \"redis-cli\", \"ping\"]\n")
				sb.WriteString("      interval: 1s\n")
				sb.WriteString("      timeout: 2s\n")
				sb.WriteString("      retries: 20\n")
			}
		}

		// Extract container ports
		ports := extractTargetPorts(svc.Ports)
		if len(ports) > 0 {
			sb.WriteString("    ports: !override\n")
			for _, p := range ports {
				sb.WriteString(fmt.Sprintf("      - \"%d\"\n", p))
			}
		}

		// Inject directed container env vars
		if envMap, ok := envDirectives[svcName]; ok && len(envMap) > 0 {
			sb.WriteString("    environment:\n")
			for k, v := range envMap {
				resolvedVal := strings.ReplaceAll(v, "{{id}}", bubbleID)
				sb.WriteString(fmt.Sprintf("      %s: %q\n", k, resolvedVal))
			}
		}
	}

	return sb.String(), nil
}

// WriteOverrideFile writes the generated override content to target path.
func WriteOverrideFile(targetPath, content string) error {
	return os.WriteFile(targetPath, []byte(content), 0644)
}

var portPattern = regexp.MustCompile(`^(?:[0-9.]+:)?(?:[0-9]+:)?([0-9]+)(?:/[a-z]+)?$`)

func extractTargetPorts(ports []any) []int {
	var targets []int
	seen := make(map[int]bool)

	for _, p := range ports {
		switch v := p.(type) {
		case int:
			if !seen[v] {
				seen[v] = true
				targets = append(targets, v)
			}
		case string:
			// Formats: "target", "published:target", "hostIP:published:target/protocol"
			m := portPattern.FindStringSubmatch(v)
			if len(m) == 2 {
				portNum, _ := strconv.Atoi(m[1])
				if portNum > 0 && !seen[portNum] {
					seen[portNum] = true
					targets = append(targets, portNum)
				}
			}
		case map[string]any:
			if target, ok := v["target"].(int); ok {
				if !seen[target] {
					seen[target] = true
					targets = append(targets, target)
				}
			}
		}
	}

	return targets
}
